language: java
env:
  global:
  - secure: db/n3YTrUt/0FUmceSFb6CyyS9rKQ7Zw292wBJRi+yjyeDuReIz+OqZeVZaSXaVoeSR1cGCxuwignvNOd2pPiwUHjiVgui00y8OVoj9vbddncDQAtmyfdaxZbcsWpykvd/97akDtGE9MzcyVgfkuBk4iT6x0VDZ63fMR25wTk6k=
addons:
  coverity_scan:
    project:
      name: r0b3rtk/JMoribus-spring
      description: Spring integration for the JMoribus BDD framework
    notification_email: robert.kuipers@gmail.com
    build_command_prepend:
    build_command: mvn clean compile
    branch_pattern: coverity
after_success:
  - mvn clean test cobertura:cobertura coveralls:cobertura
